# Generated by Django 4.2.5 on 2024-04-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_hospital_image_hospital_location_hospital_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="contact",
            field=models.CharField(default="unknow", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hospital",
            name="information",
            field=models.TextField(default="unknown"),
            preserve_default=False,
        ),
    ]
