# Generated by Django 4.2.5 on 2024-05-25 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_hospital_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="service",
        ),
    ]
