# Generated by Django 4.2.5 on 2024-05-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_appointment_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
