# Generated by Django 4.2.5 on 2024-05-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_appointment_appointment_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospital",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
